### ISSUE TITLE
Design Document Section 6 - Project Plan

### ISSUE THREAD

**Issue by xcxpcxkes** [alphonsekoh/ICT2106-P2-05#26]
- [x] Github Project Board Monitoring
- [x] Burndown Chart Monitoring
- [x] Gantt Chart Monitoring
- [x] Agile Atam Monitoring
